NumPy Package Load

``` import numpy as np```


In [1]:
import numpy as np

In [2]:
prices = [10000, 15000, 30000, 25000]
discount_prices = []

for price in prices: 
    discount_prices.append(price * 0.9)

discount_prices

[9000.0, 13500.0, 27000.0, 22500.0]

NumPy Array


In [4]:
np_prices = np.array(prices)
np_discount_prices = np_prices * 0.9

np_discount_prices
np_discount_prices.tolist()


[9000.0, 13500.0, 27000.0, 22500.0]

In [5]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2차원 배열/ Table
sales = np.array([
    [100,120,130],
    [90,110,150],
    [80,140,160]
])

sales

array([[100, 120, 130],
       [ 90, 110, 150],
       [ 80, 140, 160]])

In [9]:
# Python 2차원 배열/ Table 
tests = [
    [100,120,130],
    [90,110,150],
    [80,140,160]
]

print(tests)
print(np.array(tests))

[[100, 120, 130], [90, 110, 150], [80, 140, 160]]
[[100 120 130]
 [ 90 110 150]
 [ 80 140 160]]


- `ndim`: dimension of array
- `shape`: structure of array rows and column
- `size`: numbers of data
- `dtype`: data type of array

In [10]:
# ndim
print(np_prices.ndim, sales.ndim)

1 2


In [11]:
# shape
np_prices.shape

(4,)

In [12]:
sales.shape

(3, 3)

In [13]:
np_prices.size

4

In [14]:
sales.size

9

In [15]:
np_prices.dtype

dtype('int64')

In [16]:
sales.dtype

dtype('int64')

NumPy Data Type
1. Int8 (2^8): -128 to 127 (total sum is 256)
2. Int16 (2^16)
3. Int32 (2^32)
4. Int64 (2^64)
5. uint8: 0 to 255 
6. uint16
7. float16
8. float32
9. float64 (NumPy Default float)
10. complex64
11. complex128
12. bool
13. str_
14. object_

NumPy - Array creation functions


In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# Same as Python range()
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 균등배열 (표준편차 등)
np.linspace(0,1,5) # make 5 numbers from 0 - 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
data= np.array([10,20,30,40,50])

In [26]:
data + 10

array([20, 30, 40, 50, 60])

In [27]:
data - 10

array([ 0, 10, 20, 30, 40])

In [28]:
data * 2

array([ 20,  40,  60,  80, 100])

In [29]:
# Calculation between arrays
quantity = np.array ([2,1,3,5,4])
unit_price = np.array([10000,15000,12000,8000,20000])

sales_prices = unit_price * quantity
sales_prices

array([20000, 15000, 36000, 40000, 80000])

Indexing and slicing

- Slicing all array
```data[:]```

- Indexing
``` sales[1, :]``` first row all data
``` sales[:, 2]``` 2nd column of all rows

Conditional Filtering

In [34]:
prices
np_prices

array([10000, 15000, 30000, 25000])

In [35]:
condition = np_prices >= 20000
condition

array([False, False,  True,  True])

Missing Value: `Null`, `none` in Python, `np.nan` in NumPy